### PR TITLE
#16: allow for admin-user shared email

### PR DESCRIPTION
**Pull request by bolorundurowb**

### CODE REVIEW

**Comment by adetola-ralph** [comment]
are we converting the user to an admin? I think we should consider multiple roles though, what do you think? @chinezenwosu @bolorundurowb @Saint-lawal

**Comment by bolorundurowb** [comment]
We aren't converting user roles, @adetola-ralph . What I am doing is allowing a user who is an admin, sign up as a regular user. It has the advantage of keeping their personal and work accounts separate instead of merging the two

**Comment by adetola-ralph** [comment]
What about regular user to admi?

**Comment by bolorundurowb** [comment]
@adetola-ralph  it works both ways, a regular user can also be added as an admin

**Comment by bolorundurowb** [comment]
@adetola-ralph @Saint-lawal @chinezenwosu someone should help

**Pull request merged**
